In [3]:
import numpy as np
import pandas as pd

### 列表和NumPy数组的最主要区别在于功能性和速度。
### 列表提供基本操作，但NumPy添加了FTTs、卷积、快速搜索、基本统计、线性代数、直方图等。



#### axis 0：通常指行
#### axis 1：通常指列

In [4]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [5]:
zero=np.zeros((3,4))
len(zero)
zero.astype(np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [6]:
np.arange(3,7)

array([3, 4, 5, 6])

In [7]:
y=np.array([10,9,8,7,6,5,4,3,2,1])
y.sort()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a=np.array([(1,2,3),(4,5,6)])
b=np.append(a,[(7,8,9)])
b=np.delete(b,2)
b

array([1, 2, 4, 5, 6, 7, 8, 9])

In [16]:
#组合数组
a=np.array([1,3,5])
b=np.array([2,4,6])
#按照行堆叠数组
c=np.vstack((a,b))
#按照列堆叠数组
np.hstack((a,b))

array([1, 3, 5, 2, 4, 6])

In [18]:
a=np.array([1,2,3,4,5,6,7,8])
np.array_split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [22]:
#求矩阵的逆矩阵
np.linalg.inv([[3,1],[2,4]])

array([[ 0.4, -0.1],
       [-0.2,  0.3]])

In [24]:
#数组的转置
np.transpose([[3,1],[2,4]])

array([[3, 2],
       [1, 4]])

In [27]:
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)])
np.add(a,b)

array([[2, 4, 6],
       [5, 7, 9]])

In [29]:
np.roots([1,-2,1])

array([1., 1.])

In [32]:
# Example of np.roots
# Consider a polynomial function (x-1)^2 = x^2 - 2*x + 1
# Whose roots are 1,1
# Similarly x^2 - 4 = 0 has roots as x=±2
np.roots([1,0,-4])

array([ 2., -2.])

In [34]:
z=np.array([1,2,3,4,5,6,7,8,9,10])
c=z<6
c

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [37]:
a=np.array([1,1,2,5,8,10,11,12])
# np.std(a)
np.median(a)

6.5

In [45]:
b=np.array([(1,2,3),(4,5,6)])
# b[0:1,2]
# b[:len(b),2]
# b[0,:]
# b[0,2:]
# b[:,0]

In [47]:
c=np.array([(1,2,3),(4,5,6)])
d=c[1:2,0:2]
d

array([[4, 5]])

In [49]:
a1 = np.arange(0, 6)
a2 = np.arange(10, 16)
a3 = np.arange(20, 26)
a4 = np.arange(30, 36)
a5 = np.arange(40, 46)
a6 = np.arange(50, 56)
a = np.vstack((a1, a2, a3, a4, a5, a6))

### 小trick
### 布尔索引

In [52]:
a = np.array([1,2,3,6,1,4,1])
b = np.array([5,6,7,8,3,1,2])
other_a=a[b==1]
# other_a
other_other_a=a[b!=1]
other_other_a

array([1, 2, 3, 6, 1, 1])

In [53]:
x = np.array([4,6,8,1,2,6,9])
y = x > 5
print(x[y])
# >>> [6 8 6 9]

# Even shorter
x = np.array([1, 2, 3, 4, 4, 35, 212, 5, 5, 6])
print(x[x < 5])
# >>> [1 2 3 4 4]

[6 8 6 9]
[1 2 3 4 4]
